# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
